<?php
$events = [
    ["title" => "Marrakesh, Morocco", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/morocco-scaled.jpg", "description" => "In a bustling market in Marrakech, an elderly carpet merchant approached me and invited me to have mint tea in his shop. In between telling me about his family and his craft, he showed me the rugs woven by his grandmother. Each pattern on the rug told a story, from wedding rituals to ancient tales.", "link" => "http://localhost:8888/wordpress-3/moroco/"],
    ["title" => "County Clare, Ireland", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Ireland-scaled.jpg", "description" => "County Clare, Ireland is a picturesque region on the west coast of Ireland known for its stunning natural scenery and rich cultural heritage. It is home to the famous Cliffs of Moher, one of Europe's most spectacular sea cliffs, and the Burren, a unique karst landscape with rare plants.","link" => "http://localhost:8888/wordpress-3/irlande/"],
    ["title" => "Positano, Italy", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Italy.jpeg", "description" => "When I saw Positano for the first time, I thought I was in a fairy tale. I walked down narrow, winding streets down to the turquoise sea, past houses with coloured facades, overgrown with flowers. The scent of lemons and fresh pastries wafted through the air, and every corner offered a new panorama.","link" =>"http://localhost:8888/wordpress-3/italy/" ],
    ["title" => "Copenhagen, Denmark", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Denmark-scaled.jpg", "description" => "Copenhagen, Denmark is the capital of Denmark, combining modern architecture with a rich historical heritage. The city is known for its colorful waterfronts, such as Nyhavn, and iconic landmarks, including The Little Mermaid.","link" => "http://localhost:8888/wordpress-3/denmark/"],
    ["title" => "Brussels, Belgium", "img" =>"http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Belgium-scaled.jpg", "description" => "Brussels, Belgium is the capital of Belgium and the heart of the European Union. The city is known for its historic center with the magnificent Grand Place, one of the most beautiful squares in the world, surrounded by ornate guild houses.","link" =>"http://localhost:8888/wordpress-3/belgium/"],
    ["title" => "Liezen, Steiermark, Austria", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Austria-scaled.jpg", "description" => "Liezen, Steiermark, Austria is a picturesque town in the federal state of Styria, surrounded by the majestic Alps. Liezen is a quiet and cozy place where nature and traditional Austrian architecture harmoniously combine.","link" =>"http://localhost:8888/wordpress-3/austria/"],
    ["title" => "Cochem, RP, Germany", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Berlin.jpg","description" =>"Cochem, RP, Germany is a charming town on the banks of the Moselle River in Rhineland-Palatinate, known for its medieval charm and picturesque vineyards.The main attraction is the majestic Reichsburg Cochem, an 11th-century castle perched on a hill overlooking the town.","link" =>"http://localhost:8888/wordpress-3/germany/"],
    ["title" => "Lagos, Portugal", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Portugal.png","description" => "Lagos, Portugal is a picturesque seaside town in the Algarve region known for its golden beaches, dramatic rocky coastline and rich history.Lagos combines the atmosphere of a traditional Portuguese settlement with a modern resort. Highlights include Ponta da Piedade.","link" =>"http://localhost:8888/wordpress-3/portugal/"],
    ["title" => "Athens, Greece", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Greece-scaled.jpg","description" => "Athens, Greece is an ancient city that is considered the cradle of Western civilization and democracy. Athens is known for its historical monuments, including the famous Acropolis, home to the Parthenon, and the Agora, the former center of social life in the ancient city.","link" =>"http://localhost:8888/wordpress-3/greece/"],   
    ["title" => "Barcelona, CT, Spain", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Spain.jpeg","description" => "Barcelona, CT, Spain is a vibrant and cosmopolitan city on the Mediterranean coast, the capital of Catalonia. Barcelona is famous for its unique architecture, where Antoni Gaudi's works such as the Sagrada Familia and Parc Güell.","link"=>"http://localhost:8888/wordpress-3/spain/"],
    ["title" => "Cyprus", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/Cyprus.jpeg","description" =>  "Cyprus is a sunny island in the eastern Mediterranean known for its golden beaches, ancient history and mix of cultures. This island-state offers a rich cultural experience through a combination of Greek and Turkish heritage.","link"=>"http://localhost:8888/wordpress-3/cyprus/"],
    ["title" => "Valletta, Malta", "img" => "http://localhost:8888/wordpress-3/wp-content/uploads/2024/12/malta.jpeg","description" => "Valletta, Malta - Malta's capital city, located on a picturesque peninsula, is the historical and cultural center of the island. Famous for its Baroque architecture, this city was founded in 1566 by the Knights of St. John.","link"=>"http://localhost:8888/wordpress-3/malta/"],
    
]; 